### ISSUE TITLE
Characters show up as HTML entities

### ISSUE THREAD

**Issue by Twiebie** [anomalylabs/translator-module#1]
See the screenshot where some strings in the title have ' signs in them.

![screenshot-pyro-dev-admin-translator-1466885796037](https://cloud.githubusercontent.com/assets/903653/16358937/224d19fe-3b23-11e6-81cd-7cabe0d20816.png)

**Comment by RyanThompson** [comment]
Fixed! https://github.com/pyrocms/pyrocms-theme/commit/e118eb5ee0d019a30ff7eab4f6b883a88275f6d6
