### ISSUE TITLE
Multi line translations doesn't work with a single input field

### ISSUE THREAD

**Issue by Twiebie** [anomalylabs/translator-module#2]
Breaking to a new line with for example shift-enter doesn't work as it triggers the submit.

Maybe a text area field instead of a single input field for multi line translations?

![screenshot-pyro-dev-admin-translator-translate-anomaly-module-translator-1466886170698](https://cloud.githubusercontent.com/assets/903653/16358952/8ee63082-3b23-11e6-99cc-86f3c08815b6.png)

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/translator-module/commit/c3974bed2b1f836918e176727d9e5a808766ccb7

It's HTML but I think you're right - textarea is nicer to work in.

**Comment by RyanThompson** [comment]
Also - please keep all issues for all Pyro related stuff in pyrocms/pyrocms and just mark it like [Translator Module] in the title please.

**Comment by Twiebie** [comment]
Will do - thanks!
