### ISSUE TITLE
Special char issue

### ISSUE THREAD

**Issue by ChristianGiupponi** [anomalylabs/translator-module#8]
I used the module to translate some fields and this is the result:

    Eseguire il Seed dell&#039;addon durante l&#039;installazione?
    I dati di seed aiutano a impostare l&#039;addon e a mostrarne le potenzialità

the `'` char has been escaped and in the file is saved as `&#039;`

**Comment by RyanThompson** [comment]
Where are these being seen? We will need to escape them where they're rendered.

**Comment by RyanThompson** [comment]
Also - in the future please keep everything under the pyrocms/pyrocms repository. Just prefix with [translator-module] please ^_^

**Comment by ChristianGiupponi** [comment]
Ok, other issues will be posted on the main repo!  
That is the text that shows up when trying to install a module

![schermata 2016-07-19 alle 17 30 09](https://cloud.githubusercontent.com/assets/1614796/16955884/93188176-4dd6-11e6-83ce-b0e928cb32de.png)

**Comment by RyanThompson** [comment]
This should fix that one: https://github.com/anomalylabs/addons-module/commit/3c6c91f47c2c4662f09e5c9b17ad011643fdc60d

Feel free to PR similar instances, just ping me on slack or something if you need help finding where they're located!

Thanks!
